# Generated by Django 5.2.13 on 2026-04-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('plu_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('barcode', models.CharField(max_length=100, unique=True)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['barcode'], name='inventory_barcode_04d106_idx'), models.Index(fields=['name'], name='inventory_name_2dad98_idx'), models.Index(fields=['plu_code'], name='inventory_plu_cod_8241dc_idx')],
            },
        ),
    ]
