# Generated by Django 5.2.13 on 2026-04-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
