# Generated by Django 5.2.13 on 2026-04-25 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='posuser',
            table='users',
        ),
    ]
